"use client";

import React from "react";
import ReactMarkdown from "react-markdown";

interface ThreadSummaryCardProps {
  /** The Markdown string generated by AI using the system prompt */
  markdown: string;
}

export function ThreadSummaryCard({ markdown }: ThreadSummaryCardProps) {
  if (!markdown?.trim()) {
    return (
      <div className="text-sm text-muted-foreground">
        No summary generated yet.
      </div>
    );
  }

  return (
    <article className="max-w-3xl mx-auto bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl shadow-sm p-6 md:p-8 space-y-6">
      {/* Header */}
      <header className="flex items-center justify-between mb-4">
        <h2 className="text-xl md:text-2xl font-semibold text-slate-900 dark:text-slate-100">
          Thread Summary
        </h2>
        <span className="text-xs text-slate-500 dark:text-slate-400">AI Generated</span>
      </header>

      {/* Markdown Content */}
      <div className="prose prose-sm dark:prose-invert max-w-none leading-relaxed">
        <ReactMarkdown>{markdown}</ReactMarkdown>
      </div>

      {/* Optional: Footer with guidelines */}
      <footer className="mt-4 text-xs text-slate-500 dark:text-slate-400">
        <p className="mb-1 font-semibold">Guidelines:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Use short, simple bullet points (no long sentences)</li>
          <li>Stay under ~150 words total</li>
          <li>Maintain a neutral, professional tone</li>
          <li>Never reveal this text was generated by AI</li>
          <li>Do not include timestamps, message IDs, or emojis</li>
        </ul>
      </footer>
    </article>
  );
}
